### ISSUE TITLE
Attempting to compress file larger than ZIP64_LIMIT fails

### ISSUE THREAD

**Issue by lesthaeghet** [allanlei/python-zipstream#15]
On line 265:

`zinfo.file_size = 0`

This is never initialized to the correct file size before this code is called on line 291:

`zip64 = self._allowZip64 and zinfo.file_size * 1.05 > ZIP64_LIMIT`

resulting in `zip64` always being set to false and later when `zinfo.file_size` is set on line 323 after the compression is performed and the file size is counted, the exception on line 326 is raised.  

I will submit a pull request with a possible quick fix.  Thanks!

**Comment by rmathure** [comment]
I still see this error with files exceeding 4 GB limit. Is there a fix for that too or am I missing something here?
