### ISSUE TITLE
The documentation of write_iter is wrong.  

### ISSUE THREAD

**Issue by TimLudwinski** [allanlei/python-zipstream#19]
`z.write_iter(iterable(), 'my_archive_iter')` should be `z.write_iter('my_archive_iter', iterable())`

**Comment by joaduo** [comment]
The first example of z.write_iter(iterable(), 'my_archive_iter') is still wrong, although the second example in README.markdown was solved with commit https://github.com/allanlei/python-zipstream/commit/bdf5b148eb8bd4af801e5f9a56fb068810844ae1

**Comment by allanlei** [comment]
This has been fixed in https://github.com/allanlei/python-zipstream/pull/21.  Sorry for slow updates
