### ISSUE TITLE
Python 3.5 support

### ISSUE THREAD

**Issue by aigarius** [allanlei/python-zipstream#9]
Hi, a new bug came in to Ubuntu recently - https://bugs.launchpad.net/ubuntu/+source/python-zipstream/+bug/1480548

It seems to me that Python 3.5 slightly changed the expected symantics on file-liek objects. It looks to me that simply removing the seek() function from the zipstream.PointerIO calss could do the trick. I have not investigated if there are any other problems yet as I don't have Python 3.5 yet.

**Comment by allanlei** [comment]
Yes, it seems with 3.5 ```ZipFile``` does a check to see if the fp provided is seekable by calling ```fp.seek()``` and catches ```AttributeError``` and ```OSError```.  Since there is a non-implemented ```PointerIO.seek()```, then the ```AttributeError``` never raises and instead raises argument error about ```whence```.

**Comment by allanlei** [comment]
There were 2 solutions I could see
* Implement ```seek(offset, [whence])```
* Remove ```seek()```

Chose to go with removal since ```PointerIO``` doesn't hold data so ```seek()``` doesn't seem to fit.
